---
- set_fact: ansible_aws_ssm_instance_id="{{ item.id }}"

- name: Configure server as a license slave
  command: /opt/splunk/bin/splunk edit licenser-localslave -master_uri  https://{{ license_list[0].dns }}:8089 -auth admin:{{ splunk_admin_password }}
  retries: 3
  delay: 60
  register: result
  until: result.rc == 0