---
- name: Setting host facts using key=value pairs, this format can only create strings or booleans
  set_fact:
    ansible_aws_ssm_instance_id: "{{ item.instance_id }}"

- name: Display Server Instance ID
  debug:
    msg: "The value of Server Instance Id {{ item.instance_id }}"

- name: Disable THP in the servers
  shell: |
    # echo -e '#disable THP at boot time
    # if test -f /sys/kernel/mm/transparent_hugepage/enabled; then
    # echo never > /sys/kernel/mm/transparent_hugepage/enabled
    # fi
    # if test -f /sys/kernel/mm/transparent_hugepage/defrag; then
    # echo never > /sys/kernel/mm/transparent_hugepage/defrag
    # fi' >> /etc/rc.local
    # echo never > /sys/kernel/mm/transparent_hugepage/enabled
    # echo never > /sys/kernel/mm/transparent_hugepage/defrag
    
    if [ ! -f /tmp/foo.txt ]; then
    echo "disable_thp.service not found!"
    cat >/etc/systemd/system/disable_thp.service <<EOL
    [Unit]
    Description=Disable Transparent Huge Pages (THP)
    
    [Service]
    Type=oneshot
    ExecStart=/bin/sh -c "echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/defrag"
    
    [Install]
    WantedBy=multi-user.target
    EOL
    fi
    systemctl enable disable_thp.service 2> /dev/null
    systemctl start disable_thp.service 2> /dev/null
    systemctl status disable_thp.service 2> /dev/null
  ignore_errors: true
