name: 'Run ansible commands'
description: 'Run ansible commands to set up and configure Splunk in VMs'
inputs:
  VAULT_PASS:
    description: 'Vault password shoud be taken from secrets'
    required: true

  DEPLOYMENT_ENVIORNMENT:
    description: 'Deployment Env of Infra. Expected values are ''dev'', ''test'', ''pro'''
    default: 'development'

runs:
  using: 'composite'
  steps:
    - name: Install Ansible
      shell: bash
      run: |
        # sudo apt update
        # sudo apt install software-properties-common -y
        # sudo apt-add-repository ppa:ansible/ansible -y
        # sudo apt update
        # sudo apt install ansible -y
        pip3 install jmespath boto3
        python3 -m pip install --user ansible-core==2.14.2
        ansible-galaxy collection install community.aws
        ansible-galaxy collection install community.general
        ansible-galaxy collection install ansible.posix


    - name: Version check
      shell: bash
      run: |
        ansible --version
        pip3 list
        pip list
        python -V
        python3 -V
        which python
        which python3
    

    - name: Run Ansible commands
      working-directory: ${{ github.workspace }}/ansible
      shell: bash
      run: |
        #cat ${{ github.workspace }}/ansible/env/dev01/main.yaml
        set -e
        ENVIRONMENT='${{ inputs.DEPLOYMENT_ENVIORNMENT }}'
        ENVIRONMENT_DIRECTORY=env/$ENVIRONMENT
        ls -lrt ${{ github.workspace }}/ansible/${ENVIRONMENT_DIRECTORY}/main.yaml
        echo
        ansible-playbook -i $ENVIRONMENT_DIRECTORY site.yaml