AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template for S3 bucket with private access from VPC and manual object uploads'

Parameters:
  BucketName:
    Description: 'The name of the S3 bucket'
    Type: 'String'
  VpcId:
    Description: 'The VPC ID containing the private subnets with the S3 endpoint'
    Type: 'String'

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      AccessControl: 'Private'
      VersioningConfiguration:
        Status: 'Suspended'
      LifecycleConfiguration:
        Rules:
          - Status: 'Disabled'
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'AllowVPCPrivateSubnetRead'
            Effect: 'Allow'
            Principal: '*'
            Action:
              - 's3:GetObject'
              - 's3:ListBucket'
            Resource: 
              - !Sub 'arn:aws:s3:::${S3Bucket}'
              - !Sub 'arn:aws:s3:::${S3Bucket}/*'
            Condition:
              StringEquals:
                aws:SourceVpc: !Ref VpcId

Outputs:
  BucketName:
    Description: 'The name of the created S3 bucket'
    Value: !Ref S3Bucket
             
