---
- set_fact: ansible_aws_ssm_instance_id="{{ item.id }}"

# - name: Get Splunk license
#   amazon.aws.aws_s3:
#     bucket: "{{ bucket.files }}"
#     mode: get
#     object: "{{ splunk.licenses.licenseI.bucket_dest }}"
#     dest: "{{ splunk.licenses.licenseI.instance_dest }}"
#   register: getresult

# - debug: 
#     msg="{{ getresult.msg }}" 
#   when: getresult.changed

# - name: Get Splunk license
#   amazon.aws.aws_s3:
#     bucket: "{{ bucket.files }}"
#     mode: get
#     object: "{{ splunk.licenses.licenseE.bucket_dest }}"
#     dest: "{{ splunk.licenses.licenseE.instance_dest }}"
#   register: getresult

# - debug: 
#     msg="{{ getresult.msg }}" 
#   when: getresult.changed

- name: Create license file
  template:
    src: license.j2
    dest: "{{ splunk.licenses.licenseE.instance_dest }}"
  vars:
    content: "{{ lookup('env', 'LICENSE_E24') }}"

- name: Create license file
  template:
    src: license.j2
    dest: "{{ splunk.licenses.licenseI.instance_dest }}"
  vars:
    content: "{{ lookup('env', 'LICENSE_I24') }}"

- name: Add license to Splunk
  command: /opt/splunk/bin/splunk add licenses {{ splunk.licenses.licenseI.instance_dest }} -auth admin:{{ splunk_admin_password }}
  retries: 3
  delay: 60
  register: result
  until: result.rc == 0

- debug: 
    msg="{{ result.stdout }}" 
  when: result.changed

- name: Add license to Splunk
  command: /opt/splunk/bin/splunk add licenses {{ splunk.licenses.licenseE.instance_dest }} -auth admin:{{ splunk_admin_password }}
  retries: 3
  delay: 60
  register: result
  until: result.rc == 0

- debug: 
    msg="{{ result.stdout }}" 
  when: result.changed
