---
- set_fact: ansible_aws_ssm_instance_id="{{ item.id }}"

- name: Integrate indexers with serach head cluster
  command: > 
    /opt/splunk/bin/splunk edit cluster-config -mode searchhead
    -master_uri https://{{ master_list[0].dns }}:8089
    -secret {{ splunk_cluster_password }}
    -auth admin:{{ splunk_admin_password }}
  retries: 3
  delay: 60
  register: result
  until: result.rc == 0