---
- set_fact: ansible_aws_ssm_instance_id="{{ item.id }}"

- name: Configure Splunk forwarder
  command: > 
    /opt/splunk/bin/splunk enable app SplunkForwarder -auth admin:{{ splunk_admin_password }} 
  retries: 3
  delay: 60
  register: result
  until: result.rc == 0

- name: Configure load balancing to indexers
  command: > 
    /opt/splunk/bin/splunk add forward-server "{{ indexer.dns }}":9997 -method autobalance -auth admin:{{ splunk_admin_password }} 
  retries: 3
  delay: 60
  register: result
  until: result.rc == 0
  with_items: "{{ indexer_list }}"
  loop_control:
    loop_var: indexer