---
- set_fact: ansible_aws_ssm_instance_id="{{ item.id }}"

- name: Install Java
  become: true
  yum:
    name: "{{ java_package }}"
    state: present
    update_cache: yes
  loop:
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
  loop_control:
    loop_var: java_package

- name: Configure a search head cluster
  command: > 
    /opt/splunk/bin/splunk init shcluster-config -mgmt_uri https://{{ item.dns }}:8089
    -replication_port 34567 -replication_factor 3 -conf_deploy_fetch_url https://{{ deploy_list[0].dns }}:8089
    -secret {{ splunk_cluster_password }} -shcluster_label SH_EAF -auth admin:{{ splunk_admin_password }}
  retries: 3
  delay: 60
  register: result
  until: result.rc == 0