---
- set_fact: ansible_aws_ssm_instance_id="{{ item.id }}"

- debug: 
    msg="{{  master_list[0].dns }}" 

- name: Configure a indexer slave
  command: > 
    /opt/splunk/bin/splunk edit cluster-config -mode slave
    -master_uri "https://{{ master_list[0].dns }}:8089"
    -replication_port 9887 -secret {{ splunk_cluster_password }}
    -auth admin:{{ splunk_admin_password }} 
  retries: 3
  delay: 60
  register: result
  until: result.rc == 0

- debug: 
    msg="{{ result.stdout }}" 
  when: result.changed
