---
- set_fact: ansible_aws_ssm_instance_id="{{ item.id }}"

- name: Configure a master cluster for indexers
  become_user: splunk
  command: > 
    /opt/splunk/bin/splunk edit cluster-config -mode master
    -replication_factor 3 -search_factor 2 -secret {{ splunk_cluster_password }} -cluster_label IDX_EAF
    -auth admin:{{ splunk_admin_password }}
  retries: 3
  delay: 60
  register: result
  until: result.rc == 0

- debug: 
    msg="{{ result.stdout }}" 
  when: result.changed

- name: Restart Splunk
  ansible.builtin.systemd:
    state: restarted
    name: Splunkd
  ignore_unreachable: true
  ignore_errors: true

- name: status Splunk
  shell: /opt/splunk/bin/splunk status
  register: status_output
  ignore_errors: true

- debug: 
    msg="{{ status_output.stdout }}" 
  when: status_output.changed