---
- set_fact: ansible_aws_ssm_instance_id="{{ item.id }}"

- debug: 
    msg="{{  master_list[0].dns }}" 

- name: Configure a indexer slave
  command: >  
    /opt/splunk/bin/splunk disable webserver -auth admin:{{ splunk_admin_password }}

  retries: 3
  delay: 60
  register: result
  until: result.rc == 0

- debug: 
    msg="{{ result.stdout }}" 
  when: result.changed

# - name: Mount Point Permissions for Indexers
#   command: >  
#     sudo chmod -R o+X /opt/splunk/
#     sudo chmod -R g+rX /opt/splunk/
#     sudo chown -R splunk:splunk /opt/splunk
    
#   retries: 3
#   delay: 60
#   register: result1
#   until: result1.rc == 0  

# - debug: 
#     msg="{{ result1.stdout }}" 
#   when: result1.changed
