---
- hosts: localhost
  gather_facts: false
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: "{{ lookup('env', 'S3_BUCKET_NAME') }}"
    ansible_python_interpreter: "{{ instance.python_interpreter }}"
  become: true
  tasks:
    - name: Disable THP on All the Servers
      debug:
        msg: "Will Disable THP on these servers  {{ server_list }}"
        
    - include_tasks: roles/disableTHP/tasks/main.yaml 
      with_items: "{{ server_list }}"
