---
- hosts: localhost
  gather_facts: false
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: "{{ lookup('env', 'S3_BUCKET_NAME') }}"
    ansible_python_interpreter: "{{ instance.python_interpreter }}"
  become: yes
  tasks:
    - include_tasks: roles/restart/tasks/main.yaml 
      with_items: "{{ forwarder_list }}"