---
- set_fact: ansible_aws_ssm_instance_id="{{ item.id }}"

- name: Configure Splunk deployment client
  command: > 
    /opt/splunk/bin/splunk set deploy-poll "{{ deploymentserver_list[0].dns }}":9997
    -auth admin:{{ splunk_admin_password }} 
  retries: 3
  delay: 60
  register: result
  until: result.rc == 0